### ISSUE TITLE
Breaks in Firefox

### ISSUE THREAD

**Issue by ezhik1** [DieterHolvoet/event-propagation-path#1]
```this.target``` in the polyfill is ```undefined``` and breaks in the conditional in line 6 where a new Array is returned only if ```this.target``` is null. In firefox, this.target is undefined so the variable declaration needs a short circuit operator

**Comment by ezhik1** [comment]
actually, upon further testing, the ```polyfill``` function seems to not have ```this``` scope at all. I was able to get it working after binding the definition:
```javascript
polyfill = polyfill.bind( this );
```

**Comment by ezhik1** [comment]
@DieterHolvoet sorry to bother for that minor detail :)

**Comment by DieterHolvoet** [comment]
Should be fixed
