### ISSUE TITLE
Doubt about the condition

### ISSUE THREAD

**Issue by indacloud** [DieterHolvoet/event-propagation-path#3]
I was adding your code in a project and I had some weirdness while writting tests for the function. Shouldn't the condition on line10 be `while (element.parentElement)` without the `!`?

https://github.com/DieterHolvoet/event-propagation-path/blob/bc5bab3fee225a32a694e11aee53ec45402213c2/propagationPath.js#L10

**Comment by DieterHolvoet** [comment]
I just did some tests and correct me if I'm wrong, but both ways seem to give the same result.

**Comment by indacloud** [comment]
The result should be an array of all the `parentElement`, the original version only returns an array with the target element.

https://jsbin.com/sonemun/edit?js,console,output

**Comment by DieterHolvoet** [comment]
Have you tried this with a real event? I'm testing with a `click` event in Chrome 64.

**Comment by DieterHolvoet** [comment]
I'm not saying you're wrong about the change, I just think it's curious how it has worked until now.

**Comment by DieterHolvoet** [comment]
Here's what I mean: https://jsbin.com/qedolut/edit?js,console,output

**Comment by indacloud** [comment]
Testing it in chrome on a real event implies `event.path` exists so the polyfill is not called ;)

try to change `return event.path || (event.composedPath && event.composedPath()) || polyfill();` to `return polyfill();` in both functions

**Comment by DieterHolvoet** [comment]
Of course, I'm sorry, it's friday 😛 
If you have the time to create a pull request I'll merge.

**Comment by indacloud** [comment]
I didn't fork the repo now.. feel free to fix it on yours. I just saw it and wanted to help you notice :)
